del /Q "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Campaigns\Avatar\*"
del /Q "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Campaigns\Banner\*"
del /Q "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Missions\Avatar\*"
del /Q "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Targets\*"
del /Q "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Business\ARAManager.Business.Service\Ar_Data\*"
copy "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Test.jpg" "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Campaigns\Avatar"
copy "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Test.jpg" "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Campaigns\Banner"
copy "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Test.jpg" "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Missions\Avatar"
copy "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Test.jpg" "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Targets"
copy "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\ListTargets.txt" "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Presentation\ARAManager.Presentation.Client\Ara_Data\Targets\ListTargets.txt"
copy "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Business\ARAManager.Business.Service\READ_ME.txt" "D:\Projects\ARA\1.0\src\Manager\ARAManager\ARAManager.Business\ARAManager.Business.Service\Ar_Data\\READ_ME.txt"
pause