package uit.aep06.phuctung.ara.Service;

public class MissionService { //need to extends service
	public String GetDataTarget(String targetID) {
		//Implement code to get string result from Service later
		//Now, fake data
		if (targetID.equals("2b4011ce3a034f01a68bc3e176345aeb"))
		{
			String result = "<ARResources><ARResource><ARType>ARSM-PicturesGallery</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.movierulz25.com/wp-content/uploads/2015/12/Lt_dF.png</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://www.filmhdwallpapers.com/files/Movies-001/Alvin-and-the-Chipmunks-Road-Chip-2-Wallpapers.jpg</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://watfordpalacetheatre.co.uk/media/1324/alvin-and-the-chipmunks.jpg?width=1200</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://bttm.co.uk/wp-content/uploads/2015/12/Alvin-and-the-Chipmunks-The-Road-Chip-Trailer-2-2.jpg</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>ImageSwitcher</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Youtube</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>https://www.youtube.com/watch?v=b5wxRWcKEn0</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Youtube</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Facebook</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.imdb.com/title/tt1253863/?ref_=nv_sr_1</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Facebook</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARMM-Text</ARType><CommonAttributes><Attribute><Key>Name</Key><Value>On The Road Trip</Value></Attribute><Attribute><Key>Director</Key><Value>Noam Murro</Value></Attribute><Attribute><Key>Actor</Key><Value>2014</Value></Attribute><Attribute><Key>Description</Key><Value>Ba chú sóc chuột vui nhộn Alvin, Simon và Theodore sẽ tái ngộ khán giả trong phần 4 có tên Alvin And The Chipmunks: The Road Trip. Ở phần này, cho rằng ông chủ Dave sẽ cầu hôn bạn gái và bỏ rơi mình, ba chú sóc quyết định tìm cách để khiến anh bỏ đi ý định đó. Tuy nhiên, nhiệm vụ đầu tiên là phải tìm ra Dave ở thành phố Miami xinh đẹp. Alvin And The Chipmunks sẽ đưa người xem vào một chuỗi các trường đoạn hài hước và âm nhạc sôi động, đã giúp bộ ba chinh phục trẻ em khắp thế giới ở 3 phần trước</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>TextView</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource></ARResources>";
			return result;
		} else if(targetID.equals("d43f2af209a64fe1ad69698713dd1057")) {//bôonoan
			String result = "<ARResources><ARResource><ARType>ARSM-PicturesGallery</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.movierulz25.com/wp-content/uploads/2015/12/Lt_dF.png</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://www.filmhdwallpapers.com/files/Movies-001/Alvin-and-the-Chipmunks-Road-Chip-2-Wallpapers.jpg</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://watfordpalacetheatre.co.uk/media/1324/alvin-and-the-chipmunks.jpg?width=1200</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://bttm.co.uk/wp-content/uploads/2015/12/Alvin-and-the-Chipmunks-The-Road-Chip-Trailer-2-2.jpg</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>ImageSwitcher</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Youtube</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>https://www.youtube.com/watch?v=b5wxRWcKEn0</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Youtube</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Facebook</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.imdb.com/title/tt1253863/?ref_=nv_sr_1</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Facebook</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARMM-Text</ARType><CommonAttributes><Attribute><Key>Name</Key><Value>Bố ngoan bố hư</Value></Attribute><Attribute><Key>Director</Key><Value>Sean Anders</Value></Attribute><Attribute><Key>Actor</Key><Value>Tom; Max</Value></Attribute><Attribute><Key>Description</Key><Value>Sau những bom tấn đình đám khắp toàn cầu như Terminator: Genisys hay Mission: Impossible – Rogue Nation, hãng Paramount khép lại năm 2015 thành công bằng việc dành tặng khán giả yêu điện ảnh một tác phẩm hài hước, nồng ấm tình cảm gia đình mang tên Bo ngoan bo hu. Chuyện phim hứa hẹn mang lại nhiều tiếng cười sảng khoái tới khán giả cùng người thân qua những tình huống éo le nhưng cũng rất thực tế, được đúc kết từ chính trải nghiệm của tác giả kịch bản Brian Burns. BỐ NGOAN, BỐ HƯ là cuộc chiến vô cùng đáng yêu khi anh chồng Dusty (Mark Wahlberg) với lối sống phóng túng, cực kỳ ngông cuồng, trở về để xen vào cuộc sống của vợ cũ khi hay tin nàng vừa tái hôn.</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>TextView</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource></ARResources>";
			return result;
		} else if(targetID.equals("54cd962712a54cf6bcf934bbbe688962")){//tay du ki
			String result = "<ARResources><ARResource><ARType>ARSM-PicturesGallery</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.movierulz25.com/wp-content/uploads/2015/12/Lt_dF.png</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://www.filmhdwallpapers.com/files/Movies-001/Alvin-and-the-Chipmunks-Road-Chip-2-Wallpapers.jpg</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://watfordpalacetheatre.co.uk/media/1324/alvin-and-the-chipmunks.jpg?width=1200</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://bttm.co.uk/wp-content/uploads/2015/12/Alvin-and-the-Chipmunks-The-Road-Chip-Trailer-2-2.jpg</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>ImageSwitcher</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Youtube</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>https://www.youtube.com/watch?v=b5wxRWcKEn0</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Youtube</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Facebook</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.imdb.com/title/tt1253863/?ref_=nv_sr_1</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Facebook</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARMM-Text</ARType><CommonAttributes><Attribute><Key>Name</Key><Value>On The Road Trip</Value></Attribute><Attribute><Key>Director</Key><Value>Noam Murro</Value></Attribute><Attribute><Key>Actor</Key><Value>2014</Value></Attribute><Attribute><Key>Description</Key><Value>Ba chú sóc chuột vui nhộn Alvin, Simon và Theodore sẽ tái ngộ khán giả trong phần 4 có tên Alvin And The Chipmunks: The Road Trip. Ở phần này, cho rằng ông chủ Dave sẽ cầu hôn bạn gái và bỏ rơi mình, ba chú sóc quyết định tìm cách để khiến anh bỏ đi ý định đó. Tuy nhiên, nhiệm vụ đầu tiên là phải tìm ra Dave ở thành phố Miami xinh đẹp. Alvin And The Chipmunks sẽ đưa người xem vào một chuỗi các trường đoạn hài hước và âm nhạc sôi động, đã giúp bộ ba chinh phục trẻ em khắp thế giới ở 3 phần trước</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>TextView</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource></ARResources>";
			return result;
		} else {
			String result = "<ARResources><ARResource><ARType>ARSM-PicturesGallery</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.movierulz25.com/wp-content/uploads/2015/12/Lt_dF.png</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://www.filmhdwallpapers.com/files/Movies-001/Alvin-and-the-Chipmunks-Road-Chip-2-Wallpapers.jpg</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://watfordpalacetheatre.co.uk/media/1324/alvin-and-the-chipmunks.jpg?width=1200</Value><Extras /></Attribute><Attribute><Key>URL</Key><Value>http://bttm.co.uk/wp-content/uploads/2015/12/Alvin-and-the-Chipmunks-The-Road-Chip-Trailer-2-2.jpg</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>ImageSwitcher</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Youtube</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>https://www.youtube.com/watch?v=jvB0ZrAqzkc</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Youtube</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARSM-Facebook</ARType><CommonAttributes><Attribute><Key>URL</Key><Value>http://www.imdb.com/title/tt1253863/?ref_=nv_sr_1</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>Facebook</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource><ARResource><ARType>ARMM-Text</ARType><CommonAttributes><Attribute><Key>Name</Key><Value>On The Road Trip</Value></Attribute><Attribute><Key>Director</Key><Value>Noam Murro</Value></Attribute><Attribute><Key>Actor</Key><Value>2014</Value></Attribute><Attribute><Key>Description</Key><Value>Ba chú sóc chuột vui nhộn Alvin, Simon và Theodore sẽ tái ngộ khán giả trong phần 4 có tên Alvin And The Chipmunks: The Road Trip. Ở phần này, cho rằng ông chủ Dave sẽ cầu hôn bạn gái và bỏ rơi mình, ba chú sóc quyết định tìm cách để khiến anh bỏ đi ý định đó. Tuy nhiên, nhiệm vụ đầu tiên là phải tìm ra Dave ở thành phố Miami xinh đẹp. Alvin And The Chipmunks sẽ đưa người xem vào một chuỗi các trường đoạn hài hước và âm nhạc sôi động, đã giúp bộ ba chinh phục trẻ em khắp thế giới ở 3 phần trước</Value><Extras /></Attribute></CommonAttributes><SpecialAttributes /><Tags /><Platforms><Platform><PlatformID>Android</PlatformID><Processors><Processor><ProcessorType>TextView</ProcessorType><Data /></Processor></Processors></Platform></Platforms></ARResource></ARResources>";
			return result;
		}		
	}
	
	public int checkTargetState(String id, String userID) {
		return 0;
	}
}
