//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAManager.Business.Dao.NHibernate.Transaction {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "ARAManager.Business.Dao.NHibernate.Transaction.DataExceptionStrings", typeof(DataExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the connection string {0} is invalid..
        /// </summary>
        internal static string ConnectionStringFormatException {
            get {
                return ResourceManager.GetString("ConnectionStringFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating db connection.
        /// </summary>
        internal static string DbConnectionCreationError {
            get {
                return ResourceManager.GetString("DbConnectionCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have exactly one connection string, but found {0}..
        /// </summary>
        internal static string InvalidNumberOfConnectioNStrings {
            get {
                return ResourceManager.GetString("InvalidNumberOfConnectioNStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NHibernateSessionFactory(s) couldn&apos;t be created. Please check your session factory configuration.
        /// </summary>
        internal static string InvalidSessionFactoryConfig {
            get {
                return ResourceManager.GetString("InvalidSessionFactoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session factory service available. (ServiceName = NHibernateSessionFactory).
        /// </summary>
        internal static string MissingSessionFactory {
            get {
                return ResourceManager.GetString("MissingSessionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session factory configuration found.
        /// </summary>
        internal static string NoSessionFactoryConfiguredForConnection {
            get {
                return ResourceManager.GetString("NoSessionFactoryConfiguredForConnection", resourceCulture);
            }
        }
    }
}
